"""Initial migration

Revision ID: 2c6d916a44b2
Revises: 
Create Date: 2026-04-14 00:38:09.080126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c6d916a44b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE applications ALTER COLUMN source DROP DEFAULT')
    op.alter_column('applications', 'source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PORTAL', 'EMAIL', 'MANUAL', name='applicationsource'),
               postgresql_using='UPPER(source)::applicationsource',
               existing_nullable=False)
    op.execute("ALTER TABLE applications ALTER COLUMN source SET DEFAULT 'MANUAL'::applicationsource")

    op.create_index(op.f('ix_applications_intern_id'), 'applications', ['intern_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    op.alter_column('interns', 'education_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interns', 'work_experience',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'password_changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'password_changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('interns', 'work_experience',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interns', 'education_history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_intern_id'), table_name='applications')
    op.alter_column('applications', 'source',
               existing_type=sa.Enum('PORTAL', 'EMAIL', 'MANUAL', name='applicationsource'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    # ### end Alembic commands ###
