"""add interview scheduling fields

Revision ID: 4d4d779b1f51
Revises: 2c6d916a44b2
Create Date: 2026-04-21 14:11:04.385683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4d779b1f51'
down_revision: Union[str, None] = '2c6d916a44b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_time', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('interview_venue', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'interview_venue')
    op.drop_column('applications', 'interview_time')
    # ### end Alembic commands ###
