"""add_offer_declined_and_terminated_to_enums

Revision ID: 7e3f83913854
Revises: 4d4d779b1f51
Create Date: 2026-04-25 16:27:09.543451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e3f83913854'
down_revision: Union[str, None] = '4d4d779b1f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually added: Update enums in PostgreSQL
    # Note: ADD VALUE cannot be run in a transaction block in some versions of Postgres.
    # Alembic handles this by splitting the command if needed, but we'll use op.execute.
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'Offer Declined'")
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'Terminated'")
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'OFFER_DECLINED'")
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'TERMINATED'")
    
    op.execute("ALTER TYPE templatetype ADD VALUE 'offer_declined'")
    op.execute("ALTER TYPE templatetype ADD VALUE 'terminated'")
    op.execute("ALTER TYPE templatetype ADD VALUE 'OFFER_DECLINED'")
    op.execute("ALTER TYPE templatetype ADD VALUE 'TERMINATED'")

    op.drop_column('job_posts', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
